### ISSUE TITLE
Fix things broken by @samoconnor in #135

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/HTTP.jl#141]
- [x] add server layer to enforce optional request size limits https://github.com/JuliaWeb/HTTP.jl/pull/135#discussion_r161131190 -- https://github.com/JuliaWeb/HTTP.jl/pull/135/commits/b2b5a1429f90b3e83fab74232b9cf2838626b59b
https://github.com/JuliaWeb/HTTP.jl/blob/54fd8f835fa65434b80daa1dff2e6c1b3854ec9e/src/Messages.jl#L456
- [x] iso8859_1_to_utf8 in `String(...)` base on `Content-Type`. https://github.com/JuliaWeb/HTTP.jl/pull/135#issuecomment-357144020 -- 6d978be5031bdaa1c973e0151a4fce7182d26de2 54fd8f835fa65434b80daa1dff2e6c1b3854ec9e
https://github.com/JuliaWeb/HTTP.jl/blob/54fd8f835fa65434b80daa1dff2e6c1b3854ec9e/src/Messages.jl#L400
- [x] un-deprecate the headers and body keyword arguments https://github.com/JuliaWeb/HTTP.jl/issues/141#issuecomment-358511309 6bc739f233af98668d47802d5bd2c231e9c573dc 96fc3b65183e978c1ae0d68f36eaabb11f690113
- [x] query= kw option to replace `query` part of url https://github.com/JuliaWeb/HTTP.jl/issues/141#issuecomment-358601562 -- https://github.com/JuliaWeb/HTTP.jl/commit/57ff7471e19626f678dd0561094baf4888224ab8
https://github.com/JuliaWeb/HTTP.jl/blob/57ff7471e19626f678dd0561094baf4888224ab8/src/HTTP.jl#L298
- [ ] ~~Transfer-Encoding decode~~ Moved to #217
https://github.com/JuliaWeb/HTTP.jl/blob/54fd8f835fa65434b80daa1dff2e6c1b3854ec9e/src/Messages.jl#L406
- [ ] ~~sniff/gzip detection in Messages.bodysummary?~~ https://github.com/JuliaWeb/HTTP.jl/pull/135#pullrequestreview-88376693
`Messages.bodysummary` only prints the first part of the body, so dumping a much of gziped binary isn't as bad as it was. 
https://github.com/JuliaWeb/HTTP.jl/blob/b602c4ea0cf346b35ae9bea13db2c960eee759de/src/Messages.jl#L518
- [x] Reimplement the Content-Type detection code using sniff.jl https://github.com/JuliaWeb/HTTP.jl/pull/135#issuecomment-357144020
https://github.com/JuliaWeb/HTTP.jl/blob/fdc264e6d5049b92f7ceb41c337564df72cafe79/src/ContentTypeRequest.jl#L20-L21

**Comment by EricForgy** [comment]
Tests are failing because it can't find `@info` on v0.6.

I went ahead and submitted a PR to Compat ( https://github.com/JuliaLang/Compat.jl/pull/453 ), but subsequently learned we can also use `MicroLogging`. What do you prefer to use? `Compat` or `Micrologging`?

**Comment by EricForgy** [comment]
This is with the "Quick hack" commit...

![image](https://user-images.githubusercontent.com/8954730/35034950-668bd8e4-fba2-11e7-92cd-70a33351eb0b.png)

**Comment by EricForgy** [comment]
After a fresh `Pkg.update()` and restarting the REPL, it seems to hang...

![image](https://user-images.githubusercontent.com/8954730/35035577-6cf628ea-fba4-11e7-8638-336917a052a5.png)

**Comment by samoconnor** [comment]
hmm, looks like a problem with `Distributed` on your system?
Seems ok here: https://ci.appveyor.com/project/quinnj/http-jl/build/job/yjpcpif8prnk91v6

**Comment by EricForgy** [comment]
Could be. I can run `addprocs(5)` from the REPL with no problem though 🤔

**Comment by samoconnor** [comment]
Win64 just passed: https://ci.appveyor.com/project/quinnj/http-jl/build/1.0.389/job/7tpjf61c7i5eb0ot

**Comment by samoconnor** [comment]
This build has Win32 & Win64 passing for Julia v0.6: https://ci.appveyor.com/project/quinnj/http-jl/build/1.0.391

**Comment by quinnj** [comment]
One thing I'd like to add to the list is un-deprecating the `headers` and `body` keyword arguments. I feel like there are quite a few use-cases where you need to provide one or the other, but not both (or in the case of `body`, not `headers`). I feel like these are very natural keyword arguments that users reach for instead of having to always check the docs of `HTTP.get` or whatever to remember that it's a positional arg.

**Comment by samoconnor** [comment]
> un-deprecating the headers and body keyword arguments

Agree, I'll put this in my next commit.

**Comment by quinnj** [comment]
Hmmm, not sure I like `load`; I think most users just want it to convert automatically. Perhaps we can add a new keyword so it can be turned off if desired? Happy to take a stab at this if you want.

**Comment by samoconnor** [comment]
The question is "automatically" when?

`Message.body` is a `Vector{UInt8}` field as per the RFC  [`message-body = *OCTET`](https://tools.ietf.org/html/rfc7230#section-3.3).

Other places where we used to have APIs like `takebuf_string` and `readstring`, have been deprecated in favour of `String(take!(...)` and `read(..., String)`.

I.e. the base API for `HTTP.Message.body` most consistent with the HTTP RFC and with other similar Julia things seems to be just to access the `Vector{UInt8}` field.

An API that uses knowledge of the message headers to transform the body needs to take the `HTTP.Message` as an argument. `Base.String(m::Message)` is out because that rightly produces a string representation of the entire message.

What we seem to be looking for is a function that says "get me a string representation of this Response's body using metadata from the headers to interpret the body bytes".

We could have `bodystring(::Message)::String`. My hesitation with this is that it seems to go against the flow of the `readstring` -> `read(..., String)` deprecation.

We may also want to consider an API for the [`payload body`](https://tools.ietf.org/html/rfc7230#section-3.3.1) (i.e. the `message body` with decoded Transfer-Encoding).

What about this:
```julia
payload(m::Message)::Vector{UInt8} = hasheader(m, "Transfer-Encoding") ?
                                     decode(header(m, "Transfer-Encoding"), m.body) :
                                     m.body
payload(m::Message, Type{String}) = hasheader(m, "Content-Type", "ISO-8859-1") ?
                                    return iso8859_1_to_utf8(payload(m)) :
                                    String(payload(m))
payload(m::Message, Type{T}) =
    ... various methods that figure out how to transform to type `T`
    based on Content-Type (and other headers?).
    This could include short-cut methods that know how to decode
    Transfer-Encoding and Content-Type in a single step.
    e.g. for gzip encoded JSON, or gzip encoded CSV.
```

**Comment by quinnj** [comment]
That all sounds reasonable to me. What if we just call it `HTTP.body(resp)` and `HTTP.body(resp, String)` instead?

**Comment by samoconnor** [comment]
Any place the RFC uses language or terminology with specific meanings we should be careful to follow as closely as possible to avoid confusion. In the RFC "message-body" is the raw form (possibly encoded); and "payload-body" is the pre-Transfer-Encoding form.
If we have a field called `Message.body` or a function called `body(::Message)` it should match what the RFC calls "message-body", anything else (i.e. having `body::(Message)` return the "payload body") is confusing. If we had a `Payload` type, then `body(::Payload) -> ` "payload body" would be fine.
We could rename the `payload` function to `payloadbody`, to match the RFC terminology more precisely, I'd be happy with that, but on the other hand `payload` by itself doesn't seem to lead to any ambiguity and the RFC uses just "payload" to refer to the "payload body" in some places.

54fd8f835fa65434b80daa1dff2e6c1b3854ec9e

**Comment by quinnj** [comment]
Alright, `HTTP.payload` seems fine then.

**Comment by samoconnor** [comment]
re kw args: 6bc739f 96fc3b6

**Comment by samoconnor** [comment]
See also re-introduction of `Response(status, body)` constructors: https://github.com/JuliaWeb/HTTP.jl/commit/2c14d438cf44cceb5c6bba41c51a92f8715e543a

**Comment by KristofferC** [comment]
As a HTTP noob, I thought the `query` keyword was kinda convenient but maybe there is a reason to remove it.

**Comment by samoconnor** [comment]
@KristofferC (& @quinnj) is the patch below what you're looking for with `query=` ?
i.e. the `query=` option passed to `HTTP.request` replaces the `query` part of the `url` argument.
No really important reason for the removal. I guess you could argue that the query is part of the url and that the user should do `URI(scheme="http", host="foobar.com", path="/foo", query=["'a" => 1])` or `merge(URI("http://foobar.com/foo"), query=["a" => 1])` or `"http://foobar.com/foo?$(escapeuri(["a" => 1])"`. However, I can see that `HTTP.request("GET", "http://foobar.com/foo"), query=["a" => 1])` is a nice shortcut.

```patch
--- a/src/HTTP.jl
+++ b/src/HTTP.jl
@@ -79,6 +79,10 @@ HTTP.put("http://httpbin.org/put", [], "Hello"; conf..)


+URL options
+
+ - `query = nothing`, replaces the query part of `url`.
+
 Streaming options

  - `response_stream = nothing`, a writeable `IO` stream or any `IO`-like
@@ -286,8 +290,15 @@ request(method::String, url::URI, headers::Headers, body; kw...)::Response =

 const nobody = UInt8[]

-request(method, url, h=Header[], b=nobody; headers=h, body=b, kw...)::Response =
-    request(string(method), URI(url), mkheaders(headers), body; kw...)
+function request(method, url, h=Header[], b=nobody;
+                 headers=h, body=b, query=nothing, kw...)::Response
+
+    uri = URI(url)
+    if query != nothing
+        uri = merge(uri, query=query)
+    end
+    return request(string(method), uri, mkheaders(headers), body; kw...)
+end
```

**Comment by EricForgy** [comment]
I completely uninstalled Julia and deleted all traces of v0.6, reinstalled Julia and my tests STILL won't run :(

But, tests run fine on my colleagues machines. Must be something with my machine. Argh.

**Comment by samoconnor** [comment]
@amitmurthy ? Any guesses as to the cause of @EricForgy's problem using `addprocs` as a non-admin user on windows?

**Comment by EricForgy** [comment]
> @amitmurthy ? Any guesses as to the cause of @EricForgy's problem using addprocs as a non-admin user on windows?

Just an additional note, I can `addprocs(5)` fine from the REPL without being admin, but when HTTP/tests/server.jl calls `addprocs(5)`, it hangs unless I am admin.

**Comment by EricForgy** [comment]
Question: 

HTTP.Servers module exports `Servers`, `ServerOptions` and `server`. However, HTTP.jl just calls `using Servers.listen`. Should there be a `using Servers` so we can serve with `HTTP.serve()`?

**Comment by samoconnor** [comment]
Re `listen` vs `serve`, see https://github.com/JuliaWeb/GitHub.jl/pull/102/commits/b902a681aaeaf8decd04a187035430e663088c0a
My hope is that `serve` can be deprecated and that `listen` is as convenient to use as `serve` was (while being more flexible by allowing ` ... do ::Stream`).

**Comment by EricForgy** [comment]
> My hope is that serve can be deprecated and that listen is as convenient to use as serve was (while being more flexible by allowing ... do ::Stream).

Ah. Ok. I will try to use `listen` instead 😊 

Btw, I am going to try to switch https://github.com/EricForgy/Pages.jl from HttpServer.jl to HTTP.jl and my team is waiting on me, so that is one reason why I'm trying to help out 😅

**Comment by EricForgy** [comment]
What would a minimal example using `HTTP.listen` look like?

**Comment by samoconnor** [comment]
From the doc:
https://github.com/JuliaWeb/HTTP.jl/blob/88f086a1a3920315d666b48ae720004600f4391f/src/Servers.jl#L260-L271

https://github.com/JuliaWeb/HTTP.jl/blob/88f086a1a3920315d666b48ae720004600f4391f/src/Servers.jl#L273-L277

Example in test/async.jl
https://github.com/JuliaWeb/HTTP.jl/blob/88f086a1a3920315d666b48ae720004600f4391f/test/async.jl#L14-L32

Example in GitHub.jl:
https://github.com/JuliaWeb/GitHub.jl/commit/b902a681aaeaf8decd04a187035430e663088c0a#diff-91d13e6f489f508c1d1e0f88f1e6bbb8R126

**Comment by EricForgy** [comment]
FYI: I've migrated the HTTP parts of Pages.jl from HttpServer.jl to HTTP.jl.

https://github.com/EricForgy/Pages.jl/tree/HTTP.jl

Now I need to get WebSockets working for the rest 😅

**Comment by samoconnor** [comment]
Hi @EricForgy,

Please try `HTTP.Websockets.[listen()|open()]`

See the source for function arguments:
https://github.com/JuliaWeb/HTTP.jl/blob/6c10abc83196b4fceee1059aea2453e9ad63701c/src/WebSockets.jl#L114

https://github.com/JuliaWeb/HTTP.jl/blob/6c10abc83196b4fceee1059aea2453e9ad63701c/src/WebSockets.jl#L80

Example of client in tests:
https://github.com/JuliaWeb/HTTP.jl/blob/6c10abc83196b4fceee1059aea2453e9ad63701c/test/WebSockets.jl#L7-L22

Example of client/server in discussion: https://github.com/JuliaWeb/WebSockets.jl/issues/84#issuecomment-357078969

Server:
```julia
using HTTP; HTTP.WebSockets.listen() do ws
           open(`vlc -q --play-and-exit --intf dummy -`, "w") do vlc_stdin
               while !eof(ws)
                   ogg_samples = readavailable(ws)
                   write(vlc_stdin, ogg_samples)
                   write(ws, "Streamed $(length(ogg_samples))-bytes...")
               end
           end
       end
```

Client:
```julia
julia> using HTTP; HTTP.WebSockets.open("ws://localhost:8081") do ws
           HTTP.open("GET", "http://tinyurl.com/bach-cello-suite-1-ogg"; verbose=2) do http
               while !eof(http)
                   write(ws, readavailable(http))
                   println(String(readavailable(ws)))
               end
           end
       end
```

**Comment by EricForgy** [comment]
Cool. Thank you 🙏 I will give it a try today (I'm in Bangkok).

One thing I liked about HttpServer / WebSockets was that the WS and HTTP were handled on the same port. Is that possible with HTTP.jl?

**Comment by EricForgy** [comment]
> One thing I liked about HttpServer / WebSockets was that the WS and HTTP were handled on the same port. Is that possible with HTTP.jl?

I think I know how to do this now. Will give it a try 🙏

**Comment by samoconnor** [comment]
This issue has outlived its usefulness.
Pleas open new issues if something has been missed.
See #217 re transfer encoding.
