### ISSUE TITLE
HTTP.Client functionality

### ISSUE THREAD

**Issue by quinnj** [JuliaWeb/HTTP.jl#4]
- [ ] ~~proxy stuff~~ moved to #218
- [x] multi-part encoded files
- [x] ~digest authentication~: moved to  #37 
- [ ] ~~auto-gunzip response bodys w/ gzip transfer-encoding; auto-gzip chunked transfers~~ moved to #217

**Comment by staticfloat** [comment]
I will likely end up using multipart/upload functionality in the future, so if you'd like a guinea pig to test out whatever implementation you end up writing, I am happy to volunteer.

**Comment by quinnj** [comment]
Working on multipart now; I have the basic scaffolding setup, but I need to re-architect a little because we want to make sure we do multipart as lazy as possible (the current design I have requires to build the entire multipart body upfront). Will post as things progress.

**Comment by quinnj** [comment]
Ok, just merged support for multipar in; take it for a spin @staticfloat!

**Comment by staticfloat** [comment]
Thanks @quinnj 

I'm playing around with writing a [Resumable.js](https://github.com/23/resumable.js) client/server for initiating and receiving resumable uploads over HTTP.  I'm running into some issues when trying to upload a binary file using a `Dict` as my `body` with my `POST` request.  In particular, I get:

```
ERROR: MethodError: no method matching escape(::Array{UInt8,1})
Closest candidates are:
  escape(::Any, ::Any, ::Array{String,1}) at /Users/sabae/.julia/v0.5/HTTP/src/uri.jl:172
  escape(::Any, ::Any, ::Any) at /Users/sabae/.julia/v0.5/HTTP/src/uri.jl:170
  escape(::Number) at /Users/sabae/.julia/v0.5/HTTP/src/uri.jl:160
  ...
 in sendchunks(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Dict{String,Any}, ::Dict{String,String}, ::Int64) at /Users/sabae/.julia/v0.5/HTTP/src/types.jl:352
 in body(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::HTTP.Request, ::HTTP.RequestOptions, ::Bool) at /Users/sabae/.julia/v0.5/HTTP/src/types.jl:303
 in show(::Base.TTY, ::HTTP.Request, ::HTTP.RequestOptions) at /Users/sabae/.julia/v0.5/HTTP/src/types.jl:397
 in request(::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions, ::HTTP.Connection{TCPSocket}, ::Array{HTTP.Response,1}, ::Bool, ::Bool) at /Users/sabae/.julia/v0.5/HTTP/src/client.jl:207
 in #request#32(::Array{HTTP.Response,1}, ::Bool, ::Bool, ::Function, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at/Users/sabae/.julia/v0.5/HTTP/src/client.jl:113
 in (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::HTTP.Client{Base.TTY}, ::HTTP.Request, ::HTTP.RequestOptions) at ./<missing>:0
 in #request#30(::Dict{String,String}, ::Dict{String,Any}, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::HTTP.Client{Base.TTY}, ::HTTP.Method, ::HTTP.URI) at /Users/sabae/.julia/v0.5/HTTP/src/client.jl:97
 in (::HTTP.#kw##request)(::Array{Any,1}, ::HTTP.#request, ::HTTP.Client{Base.TTY}, ::HTTP.Method, ::HTTP.URI) at ./<missing>:0
 in #post#56(::Array{Any,1}, ::Function, ::HTTP.Client{Base.TTY}, ::HTTP.URI) at /Users/sabae/.julia/v0.5/HTTP/src/client.jl:402
 in (::HTTP.#kw##post)(::Array{Any,1}, ::HTTP.#post, ::HTTP.Client{Base.TTY}, ::HTTP.URI) at ./<missing>:0
```

This is, I believe, because it's trying to escape each element of the `Dict` before upload, just like it would for a query parameter.  Is that the right thing to do?  I admit I don't know the answer.

**Comment by ignaciomartin** [comment]
What about using the client via proxy?

**Comment by samoconnor** [comment]
See #217 and #218
